/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsPopover: typeof import('./src/components/ActionsPopover.vue')['default']
    AddButtons: typeof import('./src/components/new-template/AddButtons.vue')['default']
    AppLayout: typeof import('./src/components/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('./src/components/templates/Dropdown.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Message: typeof import('primevue/message')['default']
    MessagePreview: typeof import('./src/components/templates/MessagePreview.vue')['default']
    PaginatedTable: typeof import('./src/components/PaginatedTable.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    PreviewTemplate: typeof import('./src/components/templates/PreviewTemplate.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    TemplateBody: typeof import('./src/components/new-template/TemplateBody.vue')['default']
    TemplateButton: typeof import('./src/components/new-template/TemplateButton.vue')['default']
    TemplateCard: typeof import('./src/components/templates/TemplateCard.vue')['default']
    TemplateDropdown: typeof import('./src/components/templates/TemplateDropdown.vue')['default']
    TemplateHeader: typeof import('./src/components/new-template/TemplateHeader.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
