/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButtons: typeof import('./src/components/new-template/AddButtons.vue')['default']
    AppLayout: typeof import('./src/components/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    MessagePreview: typeof import('./src/components/templates/MessagePreview.vue')['default']
    PreviewTemplate: typeof import('./src/components/templates/PreviewTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
